### ISSUE TITLE
Promote "facts!"

### ISSUE THREAD

**Issue by dennyabrain** [tattle-made/facts#18]
Our game is about image manipulation and features some techniques from OSINT work. Lets find out who all will be interested to know about this and send the game over to them.

### Features : 
- [x] https://github.com/tattle-made/facts/issues/17
- [ ] Create Interactive content for the IG audience
- [ ] Create 3 Reels announcing facts!

**Comment by dennyabrain** [comment]
linking https://github.com/tattle-made/facts/issues/17#issuecomment-1765694682

**Comment by dennyabrain** [comment]
Poynter is featuring games in the category we are building for - https://www.poynter.org/commentary/2023/spider-man-2-reporter-zelda-totk-lucky-clover-gazette/
We can a press release to them when we are ready.
